---
title: "Manuscript Figures & Tables"
subtitle: "Immigrant Arrivals"
author: "J.P. Meagher"
date: today
format:
  pdf:
    keep-tex: true
    fig-width: 6
    fig-crop: false
execute:
  echo: false
  warning: false
  message: false
knitr:
  opts_chunk:
    crop: null
    dev: "pdf"
---

```{r setup}
library(onlineMessageboardActivity)
library(dplyr)
library(ggplot2)
library(latex2exp)
library(magrittr)
library(reshape2)
library(HDInterval)

source(here::here("code_modules/plotting.R"))
```

# Appendix: Immigrant Arrivals

Circadian activity functions for immigrant and offspring intensity functions.

```{r load_models}
fit_pppm <- readRDS(here::here("models/fit_pppm.RDS"))
fit_M4 <- readRDS(here::here("models/fit_M4.RDS"))
```

```{r 99_appendix_fig-immigrant_activity_function, fig.width=6, fig.height=3}
t <- seq(0, 24, length.out = 101)
omega <- 2 * pi * (1:2) / 24

fit_pppm |>
  as.data.frame() |>
  select(starts_with("alpha")) |>
  apply(1, function(x) {
    1 + sinusoidal_function(t = t, sinusoid_coefficients = x, sinusoid_frequencies = omega)
  }) |>
  data.frame(points = "Immigrant", t = t) |>
  rbind(
    fit_M4 |>
      as.data.frame() |>
      select(starts_with("alpha")) |>
      apply(1, function(x) {
        1 + sinusoidal_function(t = t, sinusoid_coefficients = x, sinusoid_frequencies = omega[1:2])
      }) |>
      data.frame(points = "Offspring", t = t)
  ) |>
  melt(id.vars = c("points", "t")) |>
  group_by(points, t) |>
  summarise(
    average = mean(value),
    ci.low = hdi(value)[1],
    ci.up = hdi(value)[2],
    .groups = "drop"
  ) |>
  ggplot() +
  geom_hline(yintercept = 1, lty = 2) +
  geom_ribbon(aes(x = t, ymin = ci.low, ymax = ci.up, fill = points), alpha = 0.1) +
  geom_line(aes(x = t, y = average, color = points)) +
  scale_x_continuous(limits = c(0, 24), breaks = seq(0, 24, 6)) +
  my_theme +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  labs(
    title = "Absolute-time component of intensity functions",
    x = "Time (hours)",
    y = TeX("$\\alpha (t)$"),
    color = NULL,
    fill = NULL
  )
```
